
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}

baseurl: "/extreme_territories" # the subpath of your site, replace with the name of the github repository where you will host your site
url: "" # the base hostname & protocol for your site, e.g. http://github-username.io

title: LARCH7031 | Extreme Territories Studio | Grasshopper Tutorials
author: Dr.Carlos Bartesaghi Koc, Victor Calixto, Juliana Croffi, Matthew Hawker, Dr. Philip Belesky, Kar Gan, Rasoul Rafat, and Janelle Arbon.
externallink: https://bartesaghikoc.wixsite.com/academic/larch7031-extreme-territories #can include an external url here
description:  >- # this means to ignore newlines until "baseurl:"
    A repository with Grasshopper tutorials of the course LARCH7031 Extreme Territories Studio | Landscape Urbanism Program | University of Adelaide


# Build settings - no need to change these
markdown: kramdown
kramdown:
  parse_block_html: true
theme: minima
plugins:
  - jekyll-feed
