
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}

baseurl: "/extreme_territories" # the subpath of your site, replace with the name of the github repository where you will host your site
url: "" # the base hostname & protocol for your site, e.g. http://github-username.io

title: Extreme Territories | LARCH7031 | Grasshopper Tutorials
author: Victor Calixto, Juliana Croffi, Dr.Carlos Barteshagi Koc, Dr. Philip Belesky, and Matthew Hawker.
externallink: adelaide.edu.au #can include an external url here
description:  >- # this means to ignore newlines until "baseurl:"
    A repository with Grasshopper tutorials of the course Extreme Territories - LARCH7031 | Landscape Urbanism Program | University of Adelaide


# Build settings - no need to change these
markdown: kramdown
kramdown:
  parse_block_html: true
theme: minima
plugins:
  - jekyll-feed
